# Generated by Django 6.0.5 on 2026-05-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("homemade_foods", "Homemade Foods"),
                    ("fresh_groceries", "Fresh Groceries"),
                    ("traditional_snacks", "Traditional Snacks"),
                    ("kitchen_essentials", "Kitchen Essentials"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
