# Generated by Django 6.0.5 on 2026-06-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("homemade_foods", "Homemade Foods"),
                    ("fresh_groceries", "Fresh Groceries"),
                    ("traditional_snacks", "Traditional Snacks"),
                    ("kitchen_essentials", "Kitchen Essentials"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
